openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/tennisplayers/{id}/:
    get:
      operationId: RetrieveTennisPlayer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
